---
name: Deploy to Kubernetes
on:
  push:
    branches:
      - master
jobs:
  build-push-deploy:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: chrisdgenius/blog:latest
